# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrpition', models.CharField(blank=True, max_length=200)),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.DecimalField(decimal_places=1, max_digits=1)),
                ('authors', models.ManyToManyField(to='document.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subfields', models.ManyToManyField(related_name='_field_subfields_+', to='document.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('descrpition', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('descrpition', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='fields',
            field=models.ManyToManyField(to='document.Field'),
        ),
        migrations.AddField(
            model_name='document',
            name='userclasses',
            field=models.ManyToManyField(to='document.UserClass'),
        ),
    ]
