# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-create_time']},
        ),
    ]
