# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20160423_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dir',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
