# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20160424_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descrption',
            new_name='description',
        ),
    ]
