# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20160424_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
