# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20160425_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='publish_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
