# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20160425_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='url',
            new_name='link',
        ),
    ]
