# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20160425_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='projects',
            field=models.ManyToManyField(to='document.Project'),
        ),
    ]
