# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_document_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('documents', models.ManyToManyField(to='document.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('entrys', models.ManyToManyField(to='document.Entry')),
                ('exclusion_list', models.ManyToManyField(related_name='query_exclusion_list', to='document.Document')),
                ('inclusion_list', models.ManyToManyField(related_name='query_inclusion_list', to='document.Document')),
            ],
        ),
    ]
