# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_entry_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='last_search_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
